services:
  db:
    container_name: postgres-database
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/19/docker

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gis-api
    depends_on:
      db:
        condition: service_started
    command: uv run --env-file=.env python manage.py runserver 0.0.0.0:1024
    ports:
      - "1024:1024"
    volumes:
      - ./:/app/
    env_file:
      - ./.env
    restart: always

volumes:
  pgdata:
    driver: local
