# Generated by Django 6.0.6 on 2026-06-23 03:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveOceanDrifterForecast',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_query', models.DateField(verbose_name='Date of query')),
                ('drifterData', models.JSONField(verbose_name='JSON Response')),
                ('times', models.JSONField(verbose_name='Times')),
            ],
        ),
        migrations.CreateModel(
            name='Drifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('timestamp', models.TimeField(verbose_name='Time')),
                ('drifter_id', models.IntegerField(verbose_name='ID within forecast')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.liveoceandrifterforecast')),
            ],
        ),
    ]
