# Generated by Django 6.0.6 on 2026-06-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_liveoceandrifterforecast_drifter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveoceandrifterforecast',
            old_name='drifterData',
            new_name='drifters_forecast',
        ),
    ]
