# Generated by Django 6.0.6 on 2026-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_rename_drifterdata_liveoceandrifterforecast_drifters_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveoceandrifterforecast',
            name='tracks_filename',
            field=models.CharField(default='test', max_length=50, verbose_name='Tracks file name'),
            preserve_default=False,
        ),
    ]
