# Generated by Django 6.0.6 on 2026-06-23 22:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_liveoceandrifterforecast_tracks_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrifterSnapshot',
            fields=[
                ('pk', models.CompositePrimaryKey('forecast_id', 'time_index', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time_index', models.PositiveIntegerField(help_text='Zero-based index into the original time series.')),
                ('locations', django.contrib.gis.db.models.fields.MultiPointField(help_text='WGS-84 MultiPoint: one point per drifter at this time-step.', srid=4326)),
                ('drifter_ids', models.JSONField(default=list, help_text='Ordered list of drifter ID strings matching each point.')),
                ('time', models.DateTimeField(verbose_name='The timestamp within the forecast corresponding to this snapshot')),
                ('forecast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.liveoceandrifterforecast')),
            ],
            options={
                'verbose_name': 'Drifter Snapshot',
                'verbose_name_plural': 'Drifter Snapshots',
                'ordering': ['time_index'],
            },
        ),
    ]
