# Generated by Django 6.0.6 on 2026-06-24 14:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_driftersnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driftersnapshot',
            name='locations',
            field=django.contrib.gis.db.models.fields.MultiPointField(geography=True, help_text='WGS-84 MultiPoint: one point per drifter at this time-step.', srid=4326),
        ),
    ]
